
from statistics import mean, variance
from unicodedata import decimal
import numpy as np
lst = [0, 1, 2, 3, 4, 5, 6, 7, 8]
a = np.array(lst)
a = a.reshape(3, 3)
# af = a.flatten(a)
print(a)
print("=SUM")
print(list(a.sum(axis=0)), end="  ")
print(list(a.sum(axis=1)), end="  ")
print(sum(a.reshape(-1)), )
print("=STD")
print(list(a.std(axis=0)), end="  ")
print(list(a.std(axis=1)), end="  ")
print((a.reshape(-1).std()), )
print("= Min")
print(list(a.min(axis=0)), end="  ")
print(list(a.min(axis=1)), end="  ")
print(min(a.reshape(-1)), )
print("=Max")
print(list(a.max(axis=0)), end="  ")
print(type(list(a.max(axis=1))), end="  ")
print(max(a.reshape(-1)), )
print("=")
print(list(a.mean(axis=0)), end="  ")
print(list(a.mean(axis=1)), end="  ")
print(mean(a.reshape(-1)))
print("=var")
print(list(a.var(axis=0)), end="  ")
print(list(a.var(axis=1)), end="  ")
#variance = a.var()
print(a.var())
print("x"*50)
s = a.sum()
print(s)
